lib = {
    "": {
        "atakaast": ('game_n_watch.lua', 0, None),
        "auslalom": ('game_n_watch.lua', 0, None),
        "bassmate": ('game_n_watch.lua', 0, None),
        "biathlon": ('game_n_watch.lua', 0, None),
        "ehockey": ('game_n_watch.lua', 0, None),
        "gnw_ball": ('game_n_watch.lua', 0, None),
        "gnw_bfight": ('game_n_watch.lua', 0, None),
        "gnw_bfightn": ('game_n_watch.lua', 0, None),
        "gnw_bjack": ('game_n_watch.lua', 0, None),
        "gnw_boxing": ('game_n_watch.lua', 0, None),
        "gnw_bsweep": ('game_n_watch.lua', 0, None),
        "gnw_cgrab": ('game_n_watch.lua', 0, None),
        "gnw_chef": ('game_n_watch.lua', 0, None),
        "gnw_climber": ('game_n_watch.lua', 0, None),
        "gnw_climbern": ('game_n_watch.lua', 0, None),
        "gnw_dkcirc": ('game_n_watch.lua', 0, None),
        "gnw_dkhockey": ('game_n_watch.lua', 0, None),
        "gnw_dkjr": ('game_n_watch.lua', 0, None),
        "gnw_dkjrp": ('game_n_watch.lua', 0, None),
        "gnw_dkong": ('game_n_watch.lua', 0, None),
        "gnw_dkong2": ('game_n_watch.lua', 0, None),
        "gnw_dkong3": ('game_n_watch.lua', 0, None),
        "gnw_egg": ('game_n_watch.lua', 0, None),
        "gnw_fire": ('game_n_watch.lua', 0, None),
        "gnw_fireatk": ('game_n_watch.lua', 0, None),
        "gnw_fires": ('game_n_watch.lua', 0, None),
        "gnw_flagman": ('game_n_watch.lua', 0, None),
        "gnw_gcliff": ('game_n_watch.lua', 0, None),
        "gnw_ghouse": ('game_n_watch.lua', 0, None),
        "gnw_helmet": ('game_n_watch.lua', 0, None),
        "gnw_helmeto": ('game_n_watch.lua', 0, None),
        "gnw_judge": ('game_n_watch.lua', 0, None),
        "gnw_judgeo": ('game_n_watch.lua', 0, None),
        "gnw_lboat": ('game_n_watch.lua', 0, None),
        "gnw_lion": ('game_n_watch.lua', 0, None),
        "gnw_manhole": ('game_n_watch.lua', 0, None),
        "gnw_manholeg": ('game_n_watch.lua', 0, None),
        "gnw_mario": ('game_n_watch.lua', 0, None),
        "gnw_mariocm": ('game_n_watch.lua', 0, None),
        "gnw_mariocmt": ('game_n_watch.lua', 0, None),
        "gnw_mariocmta": ('game_n_watch.lua', 0, None),
        "gnw_mariotj": ('game_n_watch.lua', 0, None),
        "gnw_mbaway": ('game_n_watch.lua', 0, None),
        "gnw_mickdon": ('game_n_watch.lua', 0, None),
        "gnw_mmouse": ('game_n_watch.lua', 0, None),
        "gnw_mmousep": ('game_n_watch.lua', 0, None),
        "gnw_octopus": ('game_n_watch.lua', 0, None),
        "gnw_opanic": ('game_n_watch.lua', 0, None),
        "gnw_pchute": ('game_n_watch.lua', 0, None),
        "gnw_pinball": ('game_n_watch.lua', 0, None),
        "gnw_popeye": ('game_n_watch.lua', 0, None),
        "gnw_popeyep": ('game_n_watch.lua', 0, None),
        "gnw_rshower": ('game_n_watch.lua', 0, None),
        "gnw_sbuster": ('game_n_watch.lua', 0, None),
        "gnw_smb": ('game_n_watch.lua', 0, None),
        "gnw_smbn": ('game_n_watch.lua', 0, None),
        "gnw_snoopyp": ('game_n_watch.lua', 0, None),
        "gnw_squish": ('game_n_watch.lua', 0, None),
        "gnw_ssparky": ('game_n_watch.lua', 0, None),
        "gnw_stennis": ('game_n_watch.lua', 0, None),
        "gnw_tbridge": ('game_n_watch.lua', 0, None),
        "gnw_tfish": ('game_n_watch.lua', 0, None),
        "gnw_vermin": ('game_n_watch.lua', 0, None),
        "gnw_zelda": ('game_n_watch.lua', 0, None),
        "kbilly": ('game_n_watch.lua', 0, None),
        "kblades": ('game_n_watch.lua', 0, None),
        "kbucky": ('game_n_watch.lua', 0, None),
        "kcontra": ('game_n_watch.lua', 0, None),
        "kdribble": ('game_n_watch.lua', 0, None),
        "kgarfld": ('game_n_watch.lua', 0, None),
        "kgradius": ('game_n_watch.lua', 0, None),
        "kloneran": ('game_n_watch.lua', 0, None),
        "knfl": ('game_n_watch.lua', 0, None),
        "kosmicmt": ('game_n_watch.lua', 0, None),
        "kosmicpt": ('game_n_watch.lua', 0, None),
        "krybolov": ('game_n_watch.lua', 0, None),
        "ktmnt": ('game_n_watch.lua', 0, None),
        "ktopgun": ('game_n_watch.lua', 0, None),
        "kvakazad": ('game_n_watch.lua', 0, None),
        "morataka": ('game_n_watch.lua', 0, None),
        "nochnyev": ('game_n_watch.lua', 0, None),
        "nsmb3": ('game_n_watch.lua', 0, None),
        "nsmw": ('game_n_watch.lua', 0, None),
        "nstarfox": ('game_n_watch.lua', 0, None),
        "nummunch": ('game_n_watch.lua', 0, None),
        "nupogodi": ('game_n_watch.lua', 0, None),
        "okhota": ('game_n_watch.lua', 0, None),
        "rkosmosa": ('game_n_watch.lua', 0, None),
        "taddams": ('game_n_watch.lua', 0, None),
        "taltbeast": ('game_n_watch.lua', 0, None),
        "tapollo13": ('game_n_watch.lua', 0, None),
        "taynyoke": ('game_n_watch.lua', 0, None),
        "tbatfor": ('game_n_watch.lua', 0, None),
        "tbatman": ('game_n_watch.lua', 0, None),
        "tbatmana": ('game_n_watch.lua', 0, None),
        "tbtoads": ('game_n_watch.lua', 0, None),
        "tbttf": ('game_n_watch.lua', 0, None),
        "tddragon": ('game_n_watch.lua', 0, None),
        "tddragon3": ('game_n_watch.lua', 0, None),
        "tdennis": ('game_n_watch.lua', 0, None),
        "tdummies": ('game_n_watch.lua', 0, None),
        "tflash": ('game_n_watch.lua', 0, None),
        "tgaiden": ('game_n_watch.lua', 0, None),
        "tgaunt": ('game_n_watch.lua', 0, None),
        "tgoldeye": ('game_n_watch.lua', 0, None),
        "tgoldnaxe": ('game_n_watch.lua', 0, None),
        "thalone": ('game_n_watch.lua', 0, None),
        "thalone2": ('game_n_watch.lua', 0, None),
        "thook": ('game_n_watch.lua', 0, None),
        "tigarden": ('game_n_watch.lua', 0, None),
        "tinday": ('game_n_watch.lua', 0, None),
        "tjdredd": ('game_n_watch.lua', 0, None),
        "tjpark": ('game_n_watch.lua', 0, None),
        "tkarnov": ('game_n_watch.lua', 0, None),
        "tkazaam": ('game_n_watch.lua', 0, None),
        "tmchammer": ('game_n_watch.lua', 0, None),
        "tmkombat": ('game_n_watch.lua', 0, None),
        "tnmarebc": ('game_n_watch.lua', 0, None),
        "topaliens": ('game_n_watch.lua', 0, None),
        "trobhood": ('game_n_watch.lua', 0, None),
        "trobocop2": ('game_n_watch.lua', 0, None),
        "trobocop3": ('game_n_watch.lua', 0, None),
        "trockteer": ('game_n_watch.lua', 0, None),
        "trshutvoy": ('game_n_watch.lua', 0, None),
        "trspacmis": ('game_n_watch.lua', 0, None),
        "trspider": ('game_n_watch.lua', 0, None),
        "trsrescue": ('game_n_watch.lua', 0, None),
        "trthuball": ('game_n_watch.lua', 0, None),
        "tsddragon": ('game_n_watch.lua', 0, None),
        "tsf2010": ('game_n_watch.lua', 0, None),
        "tsfight2": ('game_n_watch.lua', 0, None),
        "tshadow": ('game_n_watch.lua', 0, None),
        "tsharr2": ('game_n_watch.lua', 0, None),
        "tsjam": ('game_n_watch.lua', 0, None),
        "tskelwarr": ('game_n_watch.lua', 0, None),
        "tsonic": ('game_n_watch.lua', 0, None),
        "tsonic2": ('game_n_watch.lua', 0, None),
        "tspidman": ('game_n_watch.lua', 0, None),
        "tstrider": ('game_n_watch.lua', 0, None),
        "tswampt": ('game_n_watch.lua', 0, None),
        "ttransf2": ('game_n_watch.lua', 0, None),
        "tvindictr": ('game_n_watch.lua', 0, None),
        "twworld": ('game_n_watch.lua', 0, None),
        "txmen": ('game_n_watch.lua', 0, None),
        "txmenpx": ('game_n_watch.lua', 0, None),
        "vespovar": ('game_n_watch.lua', 0, None),
        "vfutbol": ('game_n_watch.lua', 0, None),
    },

    "a800_flop": {
        "a130xe": ('a800_flop.lua', 0, None),
        "a400": ('a800_flop.lua', 0, None),
        "a400pal": ('a800_flop.lua', 0, None),
        "a600xl": ('a800_flop.lua', 0, None),
        "a65xe": ('a800_flop.lua', 0, None),
        "a65xea": ('a800_flop.lua', 0, None),
        "a800": ('a800_flop.lua', 0, None),
        "a800pal": ('a800_flop.lua', 0, None),
        "a800xe": ('a800_flop.lua', 0, None),
        "a800xl": ('a800_flop.lua', 0, None),
        "a800xlp": ('a800_flop.lua', 0, None),
        "a1200xl": ('a800_flop.lua', 0, None),
    },

    "bbc_cass": {
        "bbca": ('bbc_cass.lua', 1, None),
        "bbcb": ('bbc_cass.lua', 1, None),
        "bbcb_no": ('bbc_cass.lua', 1, None),
        "bbcm": ('bbc_cass.lua', 1, None),
        "electron": ('bbc_cass.lua', 1, None),
        "electron64": ('bbc_cass.lua', 1, None),
        "electronsp": ('bbc_cass.lua', 1, None),
        "electront": ('bbc_cass.lua', 1, None),
    },

    "bbcb_flop": {
        "bbcb": ('bbcb_flop.lua', 0, None),
        "bbcb_de": ('bbcb_flop.lua', 0, None),
        "bbcb_no": ('bbcb_flop.lua', 0, None),
        "bbcb_us": ('bbcb_flop.lua', 0, None),
        "bbcbp": ('bbcb_flop.lua', 0, None),
        "bbcbp128": ('bbcb_flop.lua', 0, None),
        "bbcm": ('bbcb_flop.lua', 0, None),
        "bbcm512": ('bbcb_flop.lua', 0, None),
        "bbcmt": ('bbcb_flop.lua', 0, None),
        "ltmpbp": ('bbcb_flop.lua', 0, None),
        "ltmpm": ('bbcb_flop.lua', 0, None),
        "torchf": ('bbcb_flop.lua', 0, None),
        "torchh": ('bbcb_flop.lua', 0, None),
        "torch301": ('bbcb_flop.lua', 0, None),
        "torch725": ('bbcb_flop.lua', 0, None),
    },

    "bbcb_flop_orig": {
        "bbcb": ('bbcb_flop.lua', 0, None),
        "bbcb_de": ('bbcb_flop.lua', 0, None),
        "bbcb_no": ('bbcb_flop.lua', 0, None),
        "bbcb_us": ('bbcb_flop.lua', 0, None),
        "bbcbp": ('bbcb_flop.lua', 0, None),
        "bbcbp128": ('bbcb_flop.lua', 0, None),
        "bbcm": ('bbcb_flop.lua', 0, None),
        "bbcm512": ('bbcb_flop.lua', 0, None),
        "bbcmt": ('bbcb_flop.lua', 0, None),
        "ltmpbp": ('bbcb_flop.lua', 0, None),
        "ltmpm": ('bbcb_flop.lua', 0, None),
        "torchf": ('bbcb_flop.lua', 0, None),
        "torchh": ('bbcb_flop.lua', 0, None),
        "torch301": ('bbcb_flop.lua', 0, None),
        "torch725": ('bbcb_flop.lua', 0, None),
    },

    "bbcb_flop_us": {
        "bbcb": ('bbcb_flop.lua', 0, None),
        "bbcb_de": ('bbcb_flop.lua', 0, None),
        "bbcb_no": ('bbcb_flop.lua', 0, None),
        "bbcb_us": ('bbcb_flop.lua', 0, None),
        "bbcbp": ('bbcb_flop.lua', 0, None),
        "bbcbp128": ('bbcb_flop.lua', 0, None),
        "bbcm": ('bbcb_flop.lua', 0, None),
        "bbcm512": ('bbcb_flop.lua', 0, None),
        "bbcmt": ('bbcb_flop.lua', 0, None),
        "ltmpbp": ('bbcb_flop.lua', 0, None),
        "ltmpm": ('bbcb_flop.lua', 0, None),
        "torchf": ('bbcb_flop.lua', 0, None),
        "torchh": ('bbcb_flop.lua', 0, None),
        "torch301": ('bbcb_flop.lua', 0, None),
        "torch725": ('bbcb_flop.lua', 0, None),
    },

    "c64_cass": {
        "c64": ('c64_cass.lua', 3, None),
        "c64_jp": ('c64_cass.lua', 3, None),
        "c64_se": ('c64_cass.lua', 3, None),
        "c64c_es": ('c64_cass.lua', 3, None),
        "c64c_se": ('c64_cass.lua', 3, None),
        "c64c": ('c64_cass.lua', 3, None),
        "c64cp": ('c64_cass.lua', 3, None),
        "c64g": ('c64_cass.lua', 3, None),
        "c64p": ('c64_cass.lua', 3, None),
        "c128": ('c64_cass.lua', 6, None),
        "c128d": ('c64_cass.lua', 6, None),
        "c128dp": ('c64_cass.lua', 6, None),
        "c128p": ('c64_cass.lua', 6, None),
        "c128_de": ('c64_cass.lua', 6, None),
        "c128_se": ('c64_cass.lua', 6, None),
        "c128cr": ('c64_cass.lua', 6, None),
        "c128d": ('c64_cass.lua', 6, None),
        "c128dcr": ('c64_cass.lua', 6, None),
        "c128dcr_de": ('c64_cass.lua', 6, None),
        "c128dcr_se": ('c64_cass.lua', 6, None),
        "c128dcrp": ('c64_cass.lua', 6, None),
        "c128d81": ('c64_cass.lua', 6, None),
        "dx64": ('c64_cass.lua', 3, None),
        "sx64p": ('c64_cass.lua', 6, None),
        "vip64": ('c64_cass.lua', 3, None),
    },

    "cdi": {
        "cdimono1": ('cdi.lua', 0, None),
    },

    "cgenie_cass": {
        "cgenie": ('cgenie_cass.lua', 1, "-ramsize 32k"),
        "cgenienz": ('cgenie_cass.lua', 1, "-ramsize 32k"),
    },

    "coco_flop": {
        "cd6809": ('coco_flop.lua', 0, None),
        "coco2": ('coco_flop.lua', 0, None),
        "coco2b": ('coco_flop.lua', 0, None),
        "coco2bh": ('coco_flop.lua', 0, None),
        "coco2h": ('coco_flop.lua', 0, None),
        "coco3": ('coco_flop.lua', 0, None),
        "coco3dw1": ('coco_flop.lua', 0, None),
        "coco3h": ('coco_flop.lua', 0, None),
        "coco3p": ('coco_flop.lua', 0, None),
        "cocoe": ('coco_flop.lua', 0, None),
        "cocoeh": ('coco_flop.lua', 0, None),
        "cp400": ('coco_flop.lua', 0, None),
        "cp400c2": ('coco_flop.lua', 0, None),
    },

    "cpc_cass": {
        "cpc464": ('cpc_cass.lua', 2, None),
        "cpc664": ('cpc_cass.lua', 2, None),
        "cpc6128": ('cpc_cass.lua', 2, None),
        "cpc6128s": ('cpc_cass_cpc6128s.lua', 2, None),
        "cpc6128sp": ('cpc_cass.lua', 2, None),
        "cpc464p": ('cpc_cass.lua', 2, "-cart sysukpd"),
        "cpc6128p": ('cpc_cass.lua', 2, "-cart sysukpd"),
        "cpc6128f": ('cpc_cass.lua', 2, None),
        "kccomp": ('cpc_cass.lua', 2, None),
        "al520ex": ('cpc_cass_al520ex.lua', 0, None),
    },

    "cpc_flop": {
        "cpc664": ('cpc_flop.lua', 1.5, None),
        "cpc6128": ('cpc_flop.lua', 1.5, None),
        "cpc6128s": ('cpc_flop.lua', 1.5, None),
        "cpc6128sp": ('cpc_flop.lua', 1.5, None),
        "cpc464p": ('cpc_flop.lua', 1.5, "-cart sysukpd"),
        "cpc6128p": ('cpc_flop.lua', 1.5, "-cart sysukpd"),
        "cpc6128f": ('cpc_flop.lua', 1.5, None),
        "kccomp": ('cpc_flop.lua', 1.5, None),
        "al520ex": ('cpc_flop.lua', 1.5, None),
    },

    "dragon_cass": {
        "d64plus": ('dragon_cass.lua', 4, None),
        "dgnalpha": ('dragon_cass_dgnalpha.lua', 1, None),
        "dragon200": ('dragon_cass.lua', 4, None),
        "dragon200e": ('dragon_cass.lua', 4, None),
        "dragon32": ('dragon_cass.lua', 4, None),
        "dragon64": ('dragon_cass.lua', 4, None),
        "dragon64h": ('dragon_cass.lua', 4, None),
        "tanodr64": ('dragon_cass.lua', 4, None),
        "tanodr64h": ('dragon_cass.lua', 4, None),
    },

    "electron_cass": {
        "electron": ('electron_cass.lua', 1, None),
        "electron64": ('electron_cass.lua', 1, None),
        "electronsp": ('electron_cass.lua', 1, None),
        "electront": ('electron_cass.lua', 1, None),
    },

    "electron_flop": {
        "electron": ('electron_flop.lua', 1, None),
        "electron64": ('electron_flop.lua', 1, None),
        "electronsp": ('electron_flop.lua', 1, None),
        "electront": ('electron_flop.lua', 1, None),
    },

    "fm7_cass": {
        "fm7": ('fm7_cass.lua', 3, None),
        "fm11": ('fm7_cass.lua', 3, None),
        "fm7740sx": ('fm7_cass.lua', 3, None),
        "fm77av": ('fm7_cass.lua', 3, None),
        "fm8": ('fm7_cass.lua', 3, None),
        "fmnew7": ('fm7_cass.lua', 3, None),
    },

    "juicebox": {
        "juicebox": ('juicebox.lua', 15, None),
    },

    "megacd": {
        "megacd": ('megacd.lua', 3, None),
        "32x_mcd": ('megacd.lua', 3, None),
        "megacd2": ('megacd.lua', 3, None),
        "megacda": ('megacd.lua', 3, None)
    },

    "megacdj": {
        "aiwamcd": ('megacd.lua', 3, None),
        "32x_mcdj": ('megacd.lua', 3, None),
        "laseractj": ('megacd.lua', 3, None),
        "megacd2j": ('megacd.lua', 3, None),
        "megacdj": ('megacd.lua', 3, None),
        "wmega": ('megacd.lua', 3, None),
        "wmegam2": ('megacd.lua', 3, None)
    },

    "mo5_cass": {
        "mo5": ('mo5_cass.lua', 3, None),
        "mo6": ('mo5_cass_mo6.lua', 0, None),
        "mo5e": ('mo5_cass.lua', 3, None),
        "mo5nr": ('mo5_cass_mo6.lua', 0, None),
    },

    "mo6_cass": {
        "mo6": ('mo5_cass_mo6.lua', 0, None),
        "mo5nr": ('mo5_cass_mo6.lua', 0, None),
    },

    "msx1_cass": {
        "ax150": ('msx1_cass_5.lua', 10, None),
        "ax170": ('msx1_cass_5.lua', 10, None),
        "ax350": ('msx1_cass_4.lua', 14, None),
        "ax370": ('msx1_cass.lua', 5, None),
        "bruc100": ('msx1_cass.lua', 5, None),
        "canonv10": ('msx1_cass.lua', 6, None),
        "canonv20": ('msx1_cass.lua', 6, None),
        "canonv20e": ('msx1_cass.lua', 6, None),
        "canonv20f": ('msx1_cass.lua', 6, None),
        "canonv20g": ('msx1_cass.lua', 6, None),
        "canonv20s": ('msx1_cass.lua', 6, None),
        "canonv25": ('msx1_cass.lua', 6, None),
        "canonv30": ('msx1_cass.lua', 10, None),
        "canonv30f": ('msx1_cass.lua', 10, None),
        "canonv8": ('msx1_cass.lua', 5, None),
        "cf1200": ('msx1_cass.lua', 5, None),
        "cf2000": ('msx1_cass.lua', 5, None),
        "cf2700": ('msx1_cass.lua', 5, None),
        "cf3000": ('msx1_cass.lua', 5, None),
        "cf3300": ('msx1_cass_date.lua', 12, None),
        "cpc300": ('msx1_cass.lua', 5, None),
        "cpc300e": ('msx1_cass.lua', 10, None),
        "cpc330k": ('msx1_cass.lua', 5, None),
        "cpc400": ('msx1_cass.lua', 16, None),
        "cpc400s": ('msx1_cass.lua', 16, None),
        "cpc50a": ('msx1_cass.lua', 5, None),
        "cpc50b": ('msx1_cass.lua', 5, None),
        "cpc51": ('msx1_cass.lua', 5, None),
        "cpc61": ('msx1_cass.lua', 5, None),
        "cpc88": ('msx1_cass.lua', 6, None),
        "cx5f": ('msx1_cass.lua', 5, None),
        "cx5f1": ('msx1_cass.lua', 5, None),
        "cx5m": ('msx1_cass.lua', 5, None),
        "cx5m2": ('msx1_cass.lua', 5, None),
        "cx5m128": ('msx1_cass.lua', 5, None),
        "cx7m": ('msx1_cass.lua', 5, None),
        "cx7m128": ('msx1_cass.lua', 5, None),
        "dgnmsx": ('msx1_cass.lua', 5, None),
        "dpc100": ('msx1_cass.lua', 5, None),
        "dpc200": ('msx1_cass.lua', 5, None),
        "dpc200e": ('msx1_cass.lua', 5, None),
        "expert10": ('msx1_cass.lua', 5, None),
        "expert11": ('msx1_cass.lua', 5, None),
        "expert13": ('msx1_cass.lua', 5, None),
        "expert20": ('msx1_cass.lua', 5, None),
        "expertdp": ('msx1_cass_date.lua', 14, None),
        "expertpl": ('msx1_cass_1.lua', 6, None),
        "fdpc200": ('msx1_cass.lua', 5, None),
        "fmx": ('msx1_cass.lua', 5, None),
        "fpc500": ('msx1_cass.lua', 5, None),
        "fpc900": ('msx1_cass.lua', 8, None),
        "fs1300": ('msx1_cass.lua', 5, None),
        "fs4000": ('msx1_cass_3.lua', 5, None),
        "fs4000a": ('msx1_cass_3.lua', 5, None),
        "fs4500": ('msx1_cass_4.lua', 6, None),
        "fs4600": ('msx1_cass_4.lua', 8, None),
        "fs4700": ('msx1_cass_4.lua', 5, None),
        "fs5000": ('msx1_cass.lua', 10, None),
        "fs5500f1": ('msx1_cass.lua', 14, None),
        "fs5500f2": ('msx1_cass.lua', 14, None),
        "fsa1": ('msx1_cass_F8.lua', 8, None),
        "fsa1f": ('msx1_cass_7.lua', 18, None),
        "fsa1fm": ('msx1_cass_6.lua', 19, None),
        "fsa1fx": ('msx1_cass_6.lua', 19, None),
        "fsa1mk2": ('msx1_cass_7.lua', 19, None),
        "fsa1wsx": ('msx1_cass_0.lua', 15, None),
        "fsa1wx": ('msx1_cass_9.lua', 16, None),
        "fsa1wxa": ('msx1_cass_9.lua', 16, None),
        "fspc800": ('msx1_cass.lua', 5, None),
        "fstm1": ('msx1_cass_F8.lua', 12, None),
        "gfc1080a": ('msx1_cass.lua', 5, None),
        "gsfc200": ('msx1_cass.lua', 5, None),
        "gsfc80u": ('msx1_cass.lua', 5, None),
        "hb10": ('msx1_cass.lua', 5, None),
        "hb101p": ('msx1_cass_ret.lua', 5, None),
        "hb10p": ('msx1_cass.lua', 5, None),
        "hb201": ('msx1_cass_ret.lua', 5, None),
        "hb201p": ('msx1_cass_ret.lua', 5, None),
        "hb20p": ('msx1_cass.lua', 5, None),
        "hb501p": ('msx1_cass.lua', 5, None),
        "hb55": ('msx1_cass_down_ret.lua', 5, None),
        "hb55d": ('msx1_cass_down_ret.lua', 5, None),
        "hb55p": ('msx1_cass_down_ret.lua', 5, None),
        "hb701fd": ('msx1_cass_date.lua', 16, None),
        "hb75d": ('msx1_cass_down_ret.lua', 6, None),
        "hb75p": ('msx1_cass_down_ret.lua', 6, None),
        "hbf1xd": ('msx1_cass.lua', 9, None),
        "hbf1xdj": ('msx1_cass.lua', 10, None),
        "hbf1xdm2": ('msx1_cass.lua', 12, None),
        "hbf1xv": ('msx1_cass.lua', 11, None),
        "hbf500": ('msx1_cass.lua', 7, None),
        "hbf500f": ('msx1_cass.lua', 7, None),
        "hbf700": ('msx1_cass.lua', 13, None),
        "hbf700d": ('msx1_cass.lua', 10, None),
        "hbf700f": ('msx1_cass.lua', 13, None),
        "hbf700p": ('msx1_cass.lua', 15, None),
        "hbf700s": ('msx1_cass.lua', 15, None),
        "hbf900": ('msx1_cass.lua', 8, None),
        "hbf900a": ('msx1_cass.lua', 8, None),
        "hbf9p": ('msx1_cass_down_space.lua', 16, None),
        "hbf9s": ('msx1_cass_down_space.lua', 16, None),
        "hbf9sp": ('msx1_cass_down_space.lua', 16, None),
        "hbg900ap": ('msx1_cass.lua', 8, None),
        "hbg900p": ('msx1_cass.lua', 8, None),
        "hc5": ('msx1_cass.lua', 4, None),
        "hc6": ('msx1_cass.lua', 4, None),
        "hc7": ('msx1_cass.lua', 4, None),
        "hotbi13b": ('msx1_cass.lua', 8, None),
        "hotbi13p": ('msx1_cass.lua', 8, None),
        "hotbit11": ('msx1_cass.lua', 8, None),
        "hotbit12": ('msx1_cass.lua', 8, None),
        "hx10": ('msx1_cass.lua', 6, None),
        "hx10d": ('msx1_cass.lua', 5, None),
        "hx10e": ('msx1_cass.lua', 5, None),
        "hx10f": ('msx1_cass.lua', 5, None),
        "hx10s": ('msx1_cass.lua', 5, None),
        "hx10sa": ('msx1_cass.lua', 5, None),
        "hx20": ('msx1_cass_1.lua', 7, None),
        "hx20i": ('msx1_cass_1.lua', 9, None),
        "hx21i": ('msx1_cass_1.lua', 7, None),
        "hx22i": ('msx1_cass_1.lua', 7, None),
        "hx23": ('msx1_cass_1.lua', 7, None),
        "hx23f": ('msx1_cass_1.lua', 7, None),
        "hx23i": ('msx1_cass_1.lua', 7, None),
        "hx33": ('msx1_cass_1.lua', 7, None),
        "hx34": ('msx1_cass.lua', 8, None),
        "jvchc7gb": ('msx1_cass.lua', 5, None),
        "kmc5000": ('msx1_cass.lua', 6, None),
        "mbh2": ('msx1_cass_F1.lua', 14, None),
        "mbh25": ('msx1_cass.lua', 5, None),
        "mbh50": ('msx1_cass.lua', 5, None),
        "mlf110": ('msx1_cass.lua', 5, None),
        "mlf120": ('msx1_cass_9.lua', 7, None),
        "mlf48": ('msx1_cass.lua', 5, None),
        "mlf80": ('msx1_cass.lua', 5, None),
        "mlg1": ('msx1_cass.lua', 5, None),
        "mlg10": ('msx1_cass.lua', 8, None),
        "mlg3": ('msx1_cass.lua', 10, None),
        "mlg30": ('msx1_cass.lua', 14, None),
        "mpc10": ('msx1_cass.lua', 5, None),
        "mpc100": ('msx1_cass.lua', 5, None),
        "mpc200": ('msx1_cass.lua', 5, None),
        "mpc200sp": ('msx1_cass.lua', 5, None),
        "mpc25fd": ('msx1_cass.lua', 6, None),
        "mpc64": ('msx1_cass.lua', 5, None),
        "mx10": ('msx1_cass.lua', 6, None),
        "mx101": ('msx1_cass.lua', 5, None),
        "mx15": ('msx1_cass.lua', 5, None),
        "mx15": ('msx1_cass.lua', 5, None),
        "nms801": ('msx1_cass.lua', 5, None),
        "nms8220": ('msx1_cass.lua', 5, None),
        "nms8220a": ('msx1_cass.lua', 5, None),
        "nms8245": ('msx1_cass.lua', 14, None),
        "nms8245f": ('msx1_cass.lua', 14, None),
        "nms8250": ('msx1_cass.lua', 14, None),
        "nms8250f": ('msx1_cass.lua', 14, None),
        "nms8255": ('msx1_cass.lua', 14, None),
        "nms8255f": ('msx1_cass.lua', 14, None),
        "nms8280": ('msx1_cass.lua', 14, None),
        "nms8280f": ('msx1_cass.lua', 14, None),
        "phc2": ('msx1_cass.lua', 5, None),
        "phc23": ('msx1_cass.lua', 5, None),
        "phc28": ('msx1_cass.lua', 5, None),
        "phc28l": ('msx1_cass.lua', 5, None),
        "phc28s": ('msx1_cass.lua', 5, None),
        "phc35j": ('msx1_cass.lua', 5, None),
        "phc55fd2": ('msx1_cass.lua', 11, None),
        "phc70fd": ('msx1_cass.lua', 10, None),
        "piopx7": ('msx1_cass_2.lua', 5, None),
        "piopx7uk": ('msx1_cass_2.lua', 5, None),
        "piopxv60": ('msx1_cass_2.lua', 5, None),
        "pv16": ('msx1_cass.lua', 5, None),
        "pv7": ('msx1_cass.lua', 5, None),
        "spc800": ('msx1_cass.lua', 5, None),
        "svi728": ('msx1_cass_date.lua', 14, None),
        "svi738": ('msx1_cass_date.lua', 14, None),
        "svi738ar": ('msx1_cass_date.lua', 14, None),
        "svi738dk": ('msx1_cass_date.lua', 14, None),
        "svi738pl": ('msx1_cass_date.lua', 14, None),
        "svi738sw": ('msx1_cass_date.lua', 14, None),
        "tadpc200": ('msx1_cass.lua', 5, None),
        "tpc310": ('msx1_cass.lua', 10, None),
        "tpp311": ('msx1_cass.lua', 7, None),
        "vg8000": ('msx1_cass.lua', 5, None),
        "vg8010": ('msx1_cass.lua', 5, None),
        "vg8010f": ('msx1_cass.lua', 5, None),
        "vg802000": ('msx1_cass.lua', 5, None),
        "vg802020": ('msx1_cass.lua', 5, None),
        "vg8020f": ('msx1_cass.lua', 4, None),
        "vg8230": ('msx1_cass.lua', 12, None),
        "vg8235": ('msx1_cass.lua', 6, None),
        "vg8235f": ('msx1_cass.lua', 10, None),
        "vg8240": ('msx1_cass.lua', 6, None),
        "y503iir": ('msx1_cass_date.lua', 8, None),
        "y503iir2": ('msx1_cass_date.lua', 8, None),
        "yc64": ('msx1_cass.lua', 5, None),
        "yis303": ('msx1_cass.lua', 5, None),
        "yis503": ('msx1_cass.lua', 5, None),
        "yis503f": ('msx1_cass.lua', 5, None),
        "yis503ii": ('msx1_cass.lua', 5, None),
        "yis503iir": ('msx1_cass_date.lua', 8, None),
        "yis503m": ('msx1_cass.lua', 5, None),
        "yis604": ('msx1_cass.lua', 5, None),
        "yis60464": ('msx1_cass.lua', 5, None),
    },

    "ngp": {
        "ngp": ('ngp.lua', 0, None),
        "ngpc": ('ngp.lua', 0, None),
    },

    "ngpc": {
        "ngp": ('ngp.lua', 0, None),
        "ngpc": ('ngp.lua', 0, None),
    },

    "orao": {
        "orao": ('orao_cass.lua', 0, None),
        "orao103": ('orao_cass.lua', 0, None),
    },

    "oric1_cass": {
        "oric1": ('oric1_cass.lua', 0, None),
        "orica": ('oric1_cass.lua', 0, None),
        "prav8d": ('oric1_cass.lua', 0, None),
        "prav8dd": ('oric1_cass.lua', 0, None),
        "telstrat": ('oric1_cass.lua', 0, None),
    },

    "pcecd": {
        "pce": ('pcecd.lua', 1, '-cart scdsys'),
        "tg16": ('pcecd.lua', 1, '-cart scdsys'),
        "sgx": ('pcecd.lua', 1, '-cart scdsys')
    },

    "samcoupe_flop": {
        "samcoupe": ('samcoupe_flop.lua', 3, None),
    },

    "segacd": {
        "32x_scd": ('megacd.lua', 3, None),
        "cdx": ('megacd.lua', 3, None),
        "laseract": ('megacd.lua', 3, None),
        "segacd": ('megacd.lua', 3, None),
        "segacd2": ('megacd.lua', 3, None),
        "xeye": ('megacd.lua', 3, None)
    },

    "sorcerer_cass": {
        "sorcerer": ('sorcerer_cass.lua', 2, None),
        "sorcerer2": ('sorcerer_cass.lua', 2, None),
        "sorcerera": ('sorcerer_cass.lua', 2, None),
        "sorcererb": ('sorcerer_cass.lua', 2, None),
        "sorcererd": ('sorcerer_cass.lua', 2, None),
    },

    "spectrum_cass": {
        "bk08": ('spectrum_cass.lua', 3, None),
        "blitzs": ('spectrum_cass.lua', 3, None),
        "byte": ('spectrum_cass.lua', 3, None),
        "cip03": ('spectrum_cass.lua', 3, None),
        "compani1": ('spectrum_cass.lua', 3, None),
        "dgama87": ('spectrum_cass.lua', 3, None),
        "dgama88": ('spectrum_cass.lua', 3, None),
        "dgama89": ('spectrum_cass.lua', 3, None),
        "didaktk": ('spectrum_cass.lua', 3, None),
        "didakt90": ('spectrum_cass.lua', 3, None),
        "didakm91": ('spectrum_cass.lua', 3, None),
        "didakm92": ('spectrum_cass.lua', 3, None),
        "didakm93": ('spectrum_cass.lua', 3, None),
        "expert3t": ('spectrum_cass.lua', 3, None),
        "hc85": ('spectrum_cass.lua', 3, None),
        "hc90": ('spectrum_cass.lua', 3, None),
        "hc91": ('spectrum_cass.lua', 3, None),
        "hc128": ('spectrum_cass.lua', 3, None),
        "inves": ('spectrum_cass.lua', 3, None),
        "jet": ('spectrum_cass.lua', 3, None),
        "mistrum": ('spectrum_cass.lua', 3, None),
        "orizon": ('spectrum_cass.lua', 3, None),
        "scorpio": ('spectrum_cass_scorpio.lua', 0, None),
        "sintez2": ('spectrum_cass.lua', 3, None),
        "spectrum": ('spectrum_cass.lua', 3, None),
        "specpls2": ('spectrum_cass.lua', 3, None),
        "specpl2a": ('spectrum_cass.lua', 3, None),
        "specpls3": ('spectrum_cass.lua', 3, None),
        "specpl3e": ('spectrum_cass.lua', 3, None),
        "spec128": ('spectrum_cass.lua', 3, None),
        "spec80k": ('spectrum_cass_spec80k.lua', 0, None),
        "spektrbk": ('spectrum_cass.lua', 3, None),
        "sp3eata": ('spectrum_cass.lua', 3, None),
        "sp3ezcf": ('spectrum_cass.lua', 3, None),
        "sp3e8bit": ('spectrum_cass.lua', 3, None),
        "pentagon": ('spectrum_cass.lua', 3, None),
        "pent1024": ('spectrum_cass_pent1024.lua', 0, None),
        "tc2048": ('spectrum_cass.lua', 3, None),
        "ts2068": ('spectrum_cass.lua', 3, None),
        "tk90x": ('spectrum_cass.lua', 3, None),
        "tk95": ('spectrum_cass.lua', 3, None),
        "uk2086": ('spectrum_cass.lua', 3, None),
    },
    # bk08
    # specide
    # cip01
    # ts1500

    "specpls3_flop": {
        "sp3e8bit": ('specpls3_flop.lua', 3, None),
        "sp3eata": ('specpls3_flop.lua', 3, None),
        "sp3ezcf": ('specpls3_flop.lua', 3, None),
        "specpl3e": ('specpls3_flop.lua', 3, None),
        "specpls3": ('specpls3_flop.lua', 3, None),
    },

    "super80_cass": {
        "super80": ('super80_cass.lua', 0, None),
        "super80d": ('super80_cass.lua', 0, None),
        "super80e": ('super80_cass.lua', 0, None),
        "super80r": ('super80_cass.lua', 0, None),
        "super80m": ('super80_cass.lua', 1, None),
        "super80v": ('super80_cass.lua', 0, None),
    },

    "svi318_cass": {
        "svi318": ('svi318_cass.lua', 3, None),
        "svi318n": ('svi318_cass.lua', 3, None),
        "svi328": ('svi318_cass.lua', 3, None),
        "svi328n": ('svi318_cass.lua', 3, None),
    },

    "trs80_cass": {
        "trs80": ('trs80_cass.lua', 1, None),
    },

    "timex_cass": {
        "tc2048": ('spectrum_cass.lua', 3, None),
        "ts2068": ('spectrum_cass.lua', 3, None),
        "uk2086": ('spectrum_cass.lua', 3, None),
    },

    "vector06_flop": {
        "vector06": ('vector06_flop.lua', 3, None),
    },

    "vg5k": {
        "vg5k": ('vg5k.lua', 2, None),
    },

    "vtech2_cass": {
        "laser350": ('vtech2_cass.lua', 1, None),
        "laser500": ('vtech2_cass.lua', 1, None),
        "laser700": ('vtech2_cass.lua', 1, None),
    }
}


def get_autoboot_command(soft_list_name, machine_name):
    command = ""
    try:
        autoboot_script, autoboot_delay, extra_command = lib[soft_list_name][machine_name]

        if autoboot_delay is not None:
            command = command + " -autoboot_script autoboot_script/" + autoboot_script + " -autoboot_delay " + str(
                autoboot_delay)

        if extra_command is not None:
            command = command + " " + extra_command

    except KeyError:
        pass

    return command
